### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by RyOsUkE0730** [RyOsUkE0730/protospace-37443#1]
[ProtoSpace本番環境URL](https://protospace-37443.herokuapp.com/)

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう**
コメントの投稿者名をクリックしたときに正しく遷移しません。（そのプロトタイプを投稿したユーザーの詳細ページへ遷移してしまいます。）

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by RyOsUkE0730** [comment]
## what
show.html.erb内でlink_toメソッドの修正を行いました。

## why
コメントの投稿者名をクリックしたときに正しく遷移しなかったため

**Comment by yusuketono** [comment]
@RyOsUkE0730 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
